# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
env:
  PORT: 60000
  MQTT_BROKER_URL: mqtts://mqtt.sollab.dev:8883
  MQTT_USERNAME: mqtt
  MQTT_PASSWORD: syafiq29
  MONGODB_URL: mongodb://admin:syafiq29_sollab@sollab.dev:27017/sasaqua?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
  REACT_APP_SERVER_HOSTNAME: https://api.sasaqua.sollab.dev
  REACT_APP_SERVER_PORT: 80
  REACT_APP_MQTT_HOSTNAME: mqtt.sollab.dev
  REACT_APP_MQTT_PORT: 8083
  REACT_APP_MQTT_USERNAME: mqtt
  REACT_APP_MQTT_PASSWORD: syafiq29
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: |
        cd react
        npm i
        npm run build
    - run: |
        pm2 stop 1
        pm2 stop 2
        pm2 start 1
        pm2 start 2
